import { useCallback, useEffect, useMemo, useState } from 'react';
import { Details } from './components/Details'; import { EventMap } from './components/EventMap'; import { ReportForm } from './components/ReportForm';
import { api } from './services/api'; import type { Stats, Verdict, WeatherEvent } from './types';

const verdicts: Verdict[] = ['SUPPORTED','REFUTED','MISLEADING','UNCERTAIN'];
const blank: Stats = {total_reports:0,verified_events:0,events_today:0,active_hazards:0,verdicts:{},top_event_types:{},top_affected_regions:{}};
export default function App() {
 const [events,setEvents] = useState<WeatherEvent[]>([]); const [stats,setStats] = useState<Stats>(blank); const [selected,setSelected] = useState<WeatherEvent|null>(null); const [filter,setFilter] = useState<string>('ALL'); const [connected,setConnected] = useState(false);
 const load = useCallback(async () => { try { const [e,s]=await Promise.all([api.events(),api.stats()]); setEvents(e); setStats(s); } catch { /* API may still be starting */ } }, []);
 useEffect(()=>{ load(); const ws = new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws/events`); ws.onopen=()=>setConnected(true); ws.onclose=()=>setConnected(false); ws.onmessage=(message)=>{const payload=JSON.parse(message.data); if(payload.type==='event.created'){ setEvents(old=>[payload.event,...old.filter(e=>e.event_id!==payload.event.event_id)]); load(); }}; return()=>ws.close(); },[load]);
 const visible = useMemo(()=>filter==='ALL'?events:events.filter(e=>e.verification_status===filter),[events,filter]);
 return <main><header><div><span className="eyebrow">INDIA · WEATHER SIGNALS</span><h1>National Weather <em>Intelligence</em></h1></div><div className="connection"><i className={connected?'online':''}></i>{connected?'LIVE STREAM':'CONNECTING'}</div></header>
 <section className="metrics"><Metric label="Total reports" value={stats.total_reports}/><Metric label="Verified events" value={stats.verified_events}/><Metric label="Active hazards" value={stats.active_hazards}/><Metric label="Events today" value={stats.events_today}/></section>
 <section className="workspace"><aside className="filters"><span className="eyebrow">EVENT INTELLIGENCE</span><h2>Filter signals</h2><div className="filter-group"><label>Verification status</label><button className={filter==='ALL'?'selected':''} onClick={()=>setFilter('ALL')}>All events <b>{events.length}</b></button>{verdicts.map(v=><button key={v} className={filter===v?'selected':''} onClick={()=>setFilter(v)}><span className={`dot ${v}`}></span>{v}<b>{stats.verdicts[v]??0}</b></button>)}</div><div className="legend"><label>Confidence colors</label><p><span className="dot SUPPORTED"/> Supported <span className="dot MISLEADING"/> Needs context</p></div><ReportForm done={load}/></aside>
 <section className="map-shell"><EventMap events={visible} onSelect={setSelected}/><div className="map-header"><span>{visible.length} signals displayed</span><b>deck.gl + MapLibre</b></div></section><Details event={selected} close={()=>setSelected(null)}/></section>
 <section className="feed"><div><span className="eyebrow">VERIFIED EVENT FEED</span><h2>Recent weather observations</h2></div><button className="refresh" onClick={load}>Refresh</button><div className="event-list">{visible.slice(0,5).map(event=><button className="event-row" onClick={()=>setSelected(event)} key={event.event_id}><span className={`status ${event.verification_status}`}></span><div><b>{event.event_type.replaceAll('_',' ')}</b><p>{event.location_name ?? 'Unspecified location'} · {event.source}</p></div><p className="description">{event.description}</p><strong>{Math.round(event.confidence_score*100)}%</strong></button>)}{!visible.length&&<p className="empty-feed">Waiting for reports. Submit one above or wait for the mock collector.</p>}</div></section></main>
}
function Metric({label,value}:{label:string;value:number}) { return <div className="metric"><span>{label}</span><strong>{value.toLocaleString()}</strong></div> }
